# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorLayerToDxf
                                 A QGIS plugin
 Convert a vector layer to DXF format, 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-01
        copyright            : (C) 2021 by Juan Ortiz - Vielca Ingenieros
        email                : juan.o@vielca.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VectorLayerToDxf class from file VectorLayerToDxf.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vectorlayer_dxf import VectorLayerToDxf
    return VectorLayerToDxf(iface)
